language: generic

matrix:
  include:
    - os: linux
      sudo: required
      env: PYTHON_VERSION=python2
      language: python
      python: "2.7"

env:
  global:
    - PB_VERSION=2.6.1

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after_success.sh

after_failure:
  - ./.travis/after_failure.sh

cache:
  - timeout: 300
  - directories:
    - home/travis/build/varunjain99/onnx-xla/third_party/tensorflow/bazel-genfiles/
    - home/travis/build/varunjain99/onnx-xla/third_party/tensorflow/bazel-tensorflow/
    - home/travis/build/varunjain99/onnx-xla/third_party/tensorflow/bazel-bin/
    - $BUILD_CCACHE_DIR
    - $HOME/.ccache
    - $HOME/.cache/pb
