# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from typing import (
    Iterable,
    List,
    Optional,
    Text,
    Tuple,
    cast,
)

from google.protobuf.message import (
    Message,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer,
)

from .onnx_pb2 import (
    NodeProto,
)

class OperatorStatus(int):
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> int: ...
    @classmethod
    def keys(cls) -> List[str]: ...
    @classmethod
    def values(cls) -> List[int]: ...
    @classmethod
    def items(cls) -> List[Tuple[str, int]]: ...
EXPERIMENTAL = cast(OperatorStatus, 0)
STABLE = cast(OperatorStatus, 1)

class FunctionProto(Message):
    name = ... # type: Text
    since_version = ... # type: int
    status = ... # type: OperatorStatus
    input = ... # type: RepeatedScalarFieldContainer[Text]
    output = ... # type: RepeatedScalarFieldContainer[Text]
    attribute = ... # type: RepeatedScalarFieldContainer[Text]
    doc_string = ... # type: Text
    
    @property
    def node(self) -> RepeatedCompositeFieldContainer[NodeProto]: ...
    
    def __init__(self,
        name : Optional[Text] = None,
        since_version : Optional[int] = None,
        status : Optional[OperatorStatus] = None,
        input : Optional[Iterable[Text]] = None,
        output : Optional[Iterable[Text]] = None,
        attribute : Optional[Iterable[Text]] = None,
        node : Optional[Iterable[NodeProto]] = None,
        doc_string : Optional[Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> FunctionProto: ...
    def MergeFrom(self, other_msg: Message) -> None: ...
    def CopyFrom(self, other_msg: Message) -> None: ...

class OperatorProto(Message):
    op_type = ... # type: Text
    since_version = ... # type: int
    status = ... # type: OperatorStatus
    doc_string = ... # type: Text
    
    def __init__(self,
        op_type : Optional[Text] = None,
        since_version : Optional[int] = None,
        status : Optional[OperatorStatus] = None,
        doc_string : Optional[Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> OperatorProto: ...
    def MergeFrom(self, other_msg: Message) -> None: ...
    def CopyFrom(self, other_msg: Message) -> None: ...

class OperatorSetProto(Message):
    magic = ... # type: Text
    ir_version = ... # type: int
    ir_version_prerelease = ... # type: Text
    ir_build_metadata = ... # type: Text
    domain = ... # type: Text
    opset_version = ... # type: int
    doc_string = ... # type: Text
    
    @property
    def operator(self) -> RepeatedCompositeFieldContainer[OperatorProto]: ...
    
    @property
    def functions(self) -> RepeatedCompositeFieldContainer[FunctionProto]: ...
    
    def __init__(self,
        magic : Optional[Text] = None,
        ir_version : Optional[int] = None,
        ir_version_prerelease : Optional[Text] = None,
        ir_build_metadata : Optional[Text] = None,
        domain : Optional[Text] = None,
        opset_version : Optional[int] = None,
        doc_string : Optional[Text] = None,
        operator : Optional[Iterable[OperatorProto]] = None,
        functions : Optional[Iterable[FunctionProto]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> OperatorSetProto: ...
    def MergeFrom(self, other_msg: Message) -> None: ...
    def CopyFrom(self, other_msg: Message) -> None: ...
