// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/compiler/xla/rpc/xla_service.proto

#include "tensorflow/compiler/xla/rpc/xla_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace xla {
}  // namespace xla
namespace protobuf_tensorflow_2fcompiler_2fxla_2frpc_2fxla_5fservice_2eproto {
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tensorflow/compiler/xla/rpc/xla_service.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n-tensorflow/compiler/xla/rpc/xla_servic"
      "e.proto\022\003xla\032!tensorflow/compiler/xla/xl"
      "a.proto\032&tensorflow/compiler/xla/xla_dat"
      "a.proto2\274\n\n\nXlaService\022\?\n\nUnregister\022\026.x"
      "la.UnregisterRequest\032\027.xla.UnregisterRes"
      "ponse\"\000\022Q\n\020DeconstructTuple\022\034.xla.Decons"
      "tructTupleRequest\032\035.xla.DeconstructTuple"
      "Response\"\000\0223\n\006Unpack\022\022.xla.UnpackRequest"
      "\032\023.xla.UnpackResponse\"\000\0229\n\010GetShape\022\024.xl"
      "a.GetShapeRequest\032\025.xla.GetShapeResponse"
      "\"\000\022^\n\030GetComputationGraphStats\022!.xla.Com"
      "putationGraphStatsRequest\032\035.xla.Computat"
      "ionStatsResponse\"\000\0229\n\010LoadData\022\024.xla.Loa"
      "dDataRequest\032\025.xla.LoadDataResponse\"\000\022Q\n"
      "\020TransferToClient\022\034.xla.TransferToClient"
      "Request\032\035.xla.TransferToClientResponse\"\000"
      "\022Q\n\020TransferToServer\022\034.xla.TransferToSer"
      "verRequest\032\035.xla.TransferToServerRespons"
      "e\"\000\022Q\n\020TransferToInfeed\022\034.xla.TransferTo"
      "InfeedRequest\032\035.xla.TransferToInfeedResp"
      "onse\"\000\022Z\n\023TransferFromOutfeed\022\037.xla.Tran"
      "sferFromOutfeedRequest\032 .xla.TransferFro"
      "mOutfeedResponse\"\000\022B\n\013ResetDevice\022\027.xla."
      "ResetDeviceRequest\032\030.xla.ResetDeviceResp"
      "onse\"\000\022X\n\024ComputeConstantGraph\022 .xla.Com"
      "puteConstantGraphRequest\032\034.xla.ComputeCo"
      "nstantResponse\"\000\022Q\n\020GetDeviceHandles\022\034.x"
      "la.GetDeviceHandlesRequest\032\035.xla.GetDevi"
      "ceHandlesResponse\"\000\022Z\n\023CreateChannelHand"
      "le\022\037.xla.CreateChannelHandleRequest\032 .xl"
      "a.CreateChannelHandleResponse\"\000\022@\n\014Execu"
      "teGraph\022\030.xla.ExecuteGraphRequest\032\024.xla."
      "ExecuteResponse\"\000\022X\n\024ExecuteGraphParalle"
      "l\022 .xla.ExecuteGraphParallelRequest\032\034.xl"
      "a.ExecuteParallelResponse\"\000\022Q\n\020WaitForEx"
      "ecution\022\034.xla.WaitForExecutionRequest\032\035."
      "xla.WaitForExecutionResponse\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1478);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/compiler/xla/rpc/xla_service.proto", &protobuf_RegisterTypes);
  ::protobuf_tensorflow_2fcompiler_2fxla_2fxla_2eproto::AddDescriptors();
  ::protobuf_tensorflow_2fcompiler_2fxla_2fxla_5fdata_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_tensorflow_2fcompiler_2fxla_2frpc_2fxla_5fservice_2eproto
namespace xla {

// @@protoc_insertion_point(namespace_scope)
}  // namespace xla
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
